name: itd_2
description: "fin_chicken"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: 3.8.1
 # Flutter 3.32.8

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  page_transition: 2.2.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_inappwebview: ^6.1.5
  google_fonts: ^6.3.2
  vibration: ^2.0.0
  audioplayers: ^6.1.0
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.4
  flutter_fortune_wheel: ^1.3.2
  fluttertoast: ^9.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/achievements/
    - assets/baskets/
    - assets/bg_components/
    - assets/bg_in_shop/
    - assets/general_buttons/
    - assets/bg_in_game/
    - assets/nav_bar/